# Generated by Django 4.1.4 on 2022-12-30 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('authors', models.TextField(db_index=True, null=True)),
                ('publisher', models.TextField(db_index=True, null=True)),
                ('year', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('authors', models.TextField(db_index=True, null=True)),
                ('publisher', models.TextField(db_index=True, null=True)),
                ('libgen_id', models.IntegerField(default=-1, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=5000)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('edition', models.TextField(blank=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('English', 'en'), ('Russian', 'ru'), ('French', 'fr'), ('Spanish', 'es'), ('German', 'de'), ('Italian', 'it')], default='English', max_length=50)),
                ('topic', models.TextField(default='Other')),
                ('cover_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover', models.ImageField(blank=True, max_length=5000, null=True, upload_to='covers')),
                ('identifier', models.TextField(blank=True)),
                ('md5', models.CharField(blank=True, max_length=300)),
                ('filesize', models.IntegerField()),
                ('extension', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('djvu', 'DJVU'), ('doc', 'DOC'), ('mobi', 'MOBI'), ('rar', 'RAR'), ('zip', 'ZIP'), ('azw3', 'AZW3')], default='pdf', max_length=50)),
                ('download_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('file', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('basebook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easy_book.basebook')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_exist', models.BooleanField(default=False)),
                ('cover', models.ImageField(null=True, upload_to='asset')),
            ],
            bases=('easy_book.basebook',),
        ),
        migrations.AddIndex(
            model_name='onlinebook',
            index=models.Index(fields=['libgen_id'], name='easy_book_o_libgen__0aaacd_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinebook',
            index=models.Index(fields=['slug'], name='easy_book_o_slug_04b519_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinebook',
            index=models.Index(fields=['identifier'], name='easy_book_o_identif_174fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinebook',
            index=models.Index(fields=['md5'], name='easy_book_o_md5_a8c675_idx'),
        ),
    ]
