# Generated by Django 4.1.4 on 2022-12-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='col',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='row',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='asset'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
