# Generated by Django 4.1.4 on 2022-12-30 10:51

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_book', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
      ALTER TABLE easy_book_onlinebook ADD COLUMN document tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(identifier,'')), 'B') ||
        setweight(to_tsvector('english', coalesce(authors,'')), 'C') ||
        setweight(to_tsvector('english', coalesce(publisher,'')), 'C') ||
        setweight(to_tsvector('english', coalesce(description,'')), 'D')
      ) STORED;
    ''',

            reverse_sql='''
      ALTER TABLE easy_book_onlinebook DROP COLUMN document;
    ''',
            state_operations=[
                migrations.AddField(
                    model_name='onlinebook',
                    name='document',
                    field=django.contrib.postgres.search.SearchVectorField(null=True, blank=True),
                ),
            ]
        ),
    ]