# Generated by Django 4.1.4 on 2022-12-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_book', '0002_remove_book_col_remove_book_isbn_remove_book_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
