# Generated by Django 4.1.4 on 2022-12-27 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('easy_book', '0003_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
