# Generated by Django 4.1.4 on 2022-12-27 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('easy_book', '0004_book_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
