# Generated by Django 4.1.4 on 2022-12-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField(max_length=1)),
                ('lecturer', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('isExam', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_vahed.course')),
            ],
        ),
    ]
