# Generated by Django 4.1.4 on 2022-12-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_gpa'),
        ('easy_vahed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('time_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easy_vahed.time')),
                ('date', models.DateField()),
            ],
            bases=('easy_vahed.time',),
        ),
        migrations.RemoveField(
            model_name='time',
            name='isExam',
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
