# Generated by Django 4.1.4 on 2022-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_vahed', '0002_examtime_remove_time_isexam_alter_course_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='time',
            name='day',
        ),
        migrations.DeleteModel(
            name='ExamTime',
        ),
        migrations.AddField(
            model_name='time',
            name='day',
            field=models.ManyToManyField(blank=True, to='easy_vahed.day'),
        ),
    ]
