version: "3.8"

services:
  web:
    build: .
    volumes:
      - data:/app/data/
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  redis:
    image: redis:7.0.6-alpine
    volumes:
      - redis-data:/data/
    restart: always

volumes:
  data:
  redis-data: