version: "3.8"

services:
  redis:
    image: redis:7.0.6-alpine
    volumes:
      - redis-data:/data/
    restart: always

  rabbitmq:
    image: rabbitmq:3.11-alpine
    command: rabbitmq-server

  beat:
    build: .
    command: celery -A aut_helper beat -l info
    volumes:
      - data:/app/data/
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - rabbitmq


  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - data:/app/data/
      - .:/app/
    env_file:
      - ./.env

  web:
    build: .
    volumes:
      - data:/app/data/
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - migrate
      - redis

  bot:
    build: .
    command: python manage.py startbot
    volumes:
      - data:/app/data/
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - migrate
      - redis

  worker:
    build: .
    command: celery -A aut_helper worker -B -l info
    volumes:
      - data:/app/data/
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - migrate
      - redis
      - beat

volumes:
  data:
  redis-data: