# Generated by Django 4.1.4 on 2022-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('enter_year', models.IntegerField()),
            ],
        ),
    ]
