# Generated by Django 4.1.4 on 2022-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('d', 'واریز'), ('w', 'برداشت')], default='w', max_length=2),
        ),
    ]
